name: CI

on:
  pull_request:
  push:
    branches:
      - "*.*"
      - master

jobs:
  tests:
    runs-on: ubuntu-24.04
    services:
      redis:
        image: redis:3.2-alpine
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
        symfony-version:
          - '6.4.*'
          - '7.4.*'
        coverage: [ 'none' ]
    steps:
      -   name: "Checkout"
          uses: "actions/checkout@v2"

      -   name: "Install PHP"
          uses: "shivammathur/setup-php@v2"
          with:
            tools: flex
            php-version: "${{ matrix.php-version }}"
            extensions: redis-5.3.7
            coverage: "${{ matrix.coverage }}"

      -   name: "Install dependencies"
          uses: ramsey/composer-install@v2
          env:
            SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"

      -   name: "Run tests"
          run: composer test

  static-analysis:
    runs-on: ubuntu-24.04
    name: "Static analysis"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: ${{ matrix.php-version }}
          coverage: "none"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v4"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2

      - name: "Run code-style check"
        run: composer phpcs

      - name: "Run PHPStan check"
        run: composer phpstan
